import MainNavbar from './MainNavbar'
import SlideShow from './SlideShow'
import Information from './Information'
import BestSellers from './BestSellers'
import ShopByCategory from './ShopByCategory'
import Banner from './Banner'
import Sale from './Sale'
import Banner2 from './Banner2'
import Brands from './Brands'
import NewsLetter from './NewsLetter'
import Banner3 from './Banner3'
import Footer from './Footer'
import AboutSection from './AboutSection'
import {CareerForm} from './CareerForm'
import GetInTouch from './GetInTouch'
import MaxTechHelp from './MaxTechHelp'
import MainProducts from './MainProducts'

export {MainProducts, MaxTechHelp, GetInTouch, MainNavbar, SlideShow, Information, BestSellers, ShopByCategory, Banner, Sale, Banner2, Brands, NewsLetter, Banner3, Footer, AboutSection, CareerForm}